windows-compatible build script
ubclaunchpad/StarPort pull request #29
Opened 2023-10-14 20:55 UTC by zeowang

Added powershell script enables build on windows. (fixing the problem that blob syntax** is not usable in windows powershell)
Added new npm script option for building use the powershell script.

Run `npm run build-win` to use the script.

Note: `npm run build` will build the file `/src/foo/bar.tx` into `/dist/foo/bar/index.js`. Where as this script will build `/src/foo/bar.tx` into `/dist/foo/bar.js` which might be a little bit different.

2023-10-25 03:37 UTC, armintalaie requested changes
It looks good to me. This should be good to make it a bit simpler to run, fix the windows issue, also adds hot reload

please update the 
> - To run your API locally with a debugger, run `sam local start-api -d 5858`
in the `docs/developer.md` with better instructions to run the API.

2023-10-25 03:37 UTC, armintalaie commented on scripts/serve
> +
```suggestion
  esbuild_pid=$!
  trap "kill $esbuild_pid" SIGINT
```

2023-10-25 03:37 UTC, armintalaie commented on package.json
> +        "TEST:API": " sh ./scripts/serve",
```suggestion
        "test:api": " sh ./scripts/serve", 
```

2023-10-25 03:37 UTC, armintalaie commented on scripts/serve
> +
ctrl^c would not kill the port. i think this oughta do it

2023-11-02 20:06 UTC, armintalaie commented
@zeowang any updates on this?

2023-11-02 20:37 UTC, zeowang commented
Had added the passing parameter: when invoking npm run test:api, one can add param like `-- wiki.stack-template 8000 LAZY` to indicate parameters. If nothing is added then it will use some default template-port-dockerOption parameters in the script.

Hot reload works, just some minor issue left on ctrl-c to end the background server...

2023-11-04 18:51 UTC, armintalaie approved these changes

2023-11-04 19:41 UTC, merged