Edit user #33
ubclaunchpad/StarPort pull request #60
Opened 2024-01-20 08:16 UTC by wrfhowell

Still need to test in postman

2024-01-20 17:34 UTC, aryang13 commented on src/util/db.ts
> +    id: number;
could you make this `id: Generated<number>`

2024-01-20 17:36 UTC, aryang13 commented on src/users/editUser.ts
> +        updateUser: updatePersonData,
this object could just be named `user` since it will be easier for the frontend to modularize the code then

2024-01-20 17:42 UTC, aryang13 commented on src/users/editUser.ts
>          JSON.parse(event.body) as UpdatePerson
you can pass `updatePersonData` here instead of parsing it again

2024-01-20 17:43 UTC, aryang13 commented on src/users/editUser.ts
>          JSON.parse(event.body) as UpdatePerson
you can pass `updatePersonData` here instead of parsing it again

2024-01-20 17:44 UTC, aryang13 requested changes
could you test it in postman and make the changes below and we can merge it in

2024-01-23 02:01 UTC, armintalaie commented
Good work @wrfhowell - way to go for catching up with the codebase so quickly + keeping the PR small to make it easier to review.

--
idk if u had the chance to run the code locally with SAM but if not we can work that out. Same with DB setup for planetscale. these two will be needed to run and test locally. if u have set this up ignore the last two sentences then :))

2024-01-31 03:53 UTC, armintalaie commented
@aryang13 u gotta review again after "change requested"

2024-01-31 05:23 UTC, aryang13 approved these changes
looks good to me. @wrfhowell did you test it in postman?

2024-01-31 05:25 UTC, wrfhowell commented
> looks good to me. @wrfhowell did you test it in postman?

yea, meant to merge it on saturdya

2024-01-31 05:25 UTC, merged